language: node_js
dist: trusty
git:
  depth: 10
  sparseCheckout: tools/sparse-checkout.template
node_js:
  - "4"
cache:
  bundler: true
  apt: true
  directories:
    - node_modules
notifications:
  email:
    on_success: never
    on_failure: always
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/f5350a3bccfdf3d07867
sudo: required
branches:
  only:
    - compatibleTest
